
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java_cup.runtime.*;
import java_cup.runtime.Symbol;
import Tabla.*;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;
import Polaca.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class AnalizadorSintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolos.class;
}

  /** Default constructor. */
  @Deprecated
  public AnalizadorSintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public AnalizadorSintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\106\000\002\002\004\000\002\002\003\000\002\003" +
    "\003\000\002\003\004\000\002\005\004\000\002\005\003" +
    "\000\002\005\003\000\002\005\004\000\002\005\004\000" +
    "\002\005\003\000\002\004\005\000\002\031\002\000\002" +
    "\032\002\000\002\033\002\000\002\013\014\000\002\034" +
    "\002\000\002\012\013\000\002\035\002\000\002\017\007" +
    "\000\002\017\003\000\002\006\002\000\002\014\003\000" +
    "\002\014\005\000\002\036\002\000\002\014\006\000\002" +
    "\014\004\000\002\015\005\000\002\016\003\000\002\016" +
    "\003\000\002\016\003\000\002\016\003\000\002\016\003" +
    "\000\002\016\003\000\002\007\005\000\002\007\005\000" +
    "\002\007\003\000\002\010\005\000\002\010\005\000\002" +
    "\010\003\000\002\026\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\026\003\000\002\026\003" +
    "\000\002\021\004\000\002\022\004\000\002\020\012\000" +
    "\002\023\005\000\002\023\003\000\002\024\005\000\002" +
    "\024\003\000\002\025\003\000\002\025\003\000\002\025" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\011\005\000\002\037\002\000\002\011\013\000\002" +
    "\027\005\000\002\027\003\000\002\030\003\000\002\030" +
    "\003\000\002\030\003\000\002\030\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\172\000\016\004\006\005\022\006\004\013\005\014" +
    "\014\045\020\001\002\000\004\023\155\001\002\000\004" +
    "\032\ufff6\001\002\000\016\045\135\046\143\047\141\050" +
    "\137\051\136\052\142\001\002\000\004\031\134\001\002" +
    "\000\022\002\ufff8\004\ufff8\005\ufff8\006\ufff8\013\ufff8\014" +
    "\ufff8\035\ufff8\045\ufff8\001\002\000\022\002\ufffb\004\ufffb" +
    "\005\ufffb\006\ufffb\013\ufffb\014\ufffb\035\ufffb\045\ufffb\001" +
    "\002\000\004\002\133\001\002\000\020\002\000\004\006" +
    "\005\022\006\004\013\005\014\014\045\020\001\002\000" +
    "\004\032\073\001\002\000\004\031\072\001\002\000\022" +
    "\002\uffff\004\uffff\005\uffff\006\uffff\013\uffff\014\uffff\035" +
    "\uffff\045\uffff\001\002\000\022\002\ufffc\004\ufffc\005\ufffc" +
    "\006\ufffc\013\ufffc\014\ufffc\035\ufffc\045\ufffc\001\002\000" +
    "\004\016\025\001\002\000\004\031\024\001\002\000\004" +
    "\045\023\001\002\000\004\031\uffd3\001\002\000\022\002" +
    "\ufffd\004\ufffd\005\ufffd\006\ufffd\013\ufffd\014\ufffd\035\ufffd" +
    "\045\ufffd\001\002\000\022\032\031\044\026\045\034\046" +
    "\035\047\032\050\040\051\027\052\037\001\002\000\004" +
    "\032\053\001\002\000\036\017\uffc5\020\uffc5\021\uffc5\022" +
    "\uffc5\023\uffc5\024\uffc5\025\uffc5\026\uffc5\027\uffc5\031\uffc5" +
    "\033\uffc5\040\uffc5\041\uffc5\042\uffc5\001\002\000\036\017" +
    "\uffde\020\uffde\021\044\022\045\023\uffde\024\uffde\025\uffde" +
    "\026\uffde\027\uffde\031\uffde\033\uffde\040\uffde\041\uffde\042" +
    "\uffde\001\002\000\022\032\031\044\026\045\034\046\035" +
    "\047\032\050\040\051\027\052\037\001\002\000\036\017" +
    "\uffc8\020\uffc8\021\uffc8\022\uffc8\023\uffc8\024\uffc8\025\uffc8" +
    "\026\uffc8\027\uffc8\031\uffc8\033\uffc8\040\uffc8\041\uffc8\042" +
    "\uffc8\001\002\000\010\017\042\020\041\031\ufff7\001\002" +
    "\000\036\017\uffca\020\uffca\021\uffca\022\uffca\023\uffca\024" +
    "\uffca\025\uffca\026\uffca\027\uffca\031\uffca\033\uffca\040\uffca" +
    "\041\uffca\042\uffca\001\002\000\036\017\uffc9\020\uffc9\021" +
    "\uffc9\022\uffc9\023\uffc9\024\uffc9\025\uffc9\026\uffc9\027\uffc9" +
    "\031\uffc9\033\uffc9\040\uffc9\041\uffc9\042\uffc9\001\002\000" +
    "\036\017\uffdb\020\uffdb\021\uffdb\022\uffdb\023\uffdb\024\uffdb" +
    "\025\uffdb\026\uffdb\027\uffdb\031\uffdb\033\uffdb\040\uffdb\041" +
    "\uffdb\042\uffdb\001\002\000\036\017\uffc6\020\uffc6\021\uffc6" +
    "\022\uffc6\023\uffc6\024\uffc6\025\uffc6\026\uffc6\027\uffc6\031" +
    "\uffc6\033\uffc6\040\uffc6\041\uffc6\042\uffc6\001\002\000\036" +
    "\017\uffc7\020\uffc7\021\uffc7\022\uffc7\023\uffc7\024\uffc7\025" +
    "\uffc7\026\uffc7\027\uffc7\031\uffc7\033\uffc7\040\uffc7\041\uffc7" +
    "\042\uffc7\001\002\000\022\032\031\044\026\045\034\046" +
    "\035\047\032\050\040\051\027\052\037\001\002\000\022" +
    "\032\031\044\026\045\034\046\035\047\032\050\040\051" +
    "\027\052\037\001\002\000\036\017\uffe0\020\uffe0\021\044" +
    "\022\045\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\031" +
    "\uffe0\033\uffe0\040\uffe0\041\uffe0\042\uffe0\001\002\000\022" +
    "\032\031\044\026\045\034\046\035\047\032\050\040\051" +
    "\027\052\037\001\002\000\022\032\031\044\026\045\034" +
    "\046\035\047\032\050\040\051\027\052\037\001\002\000" +
    "\036\017\uffdd\020\uffdd\021\uffdd\022\uffdd\023\uffdd\024\uffdd" +
    "\025\uffdd\026\uffdd\027\uffdd\031\uffdd\033\uffdd\040\uffdd\041" +
    "\uffdd\042\uffdd\001\002\000\036\017\uffdc\020\uffdc\021\uffdc" +
    "\022\uffdc\023\uffdc\024\uffdc\025\uffdc\026\uffdc\027\uffdc\031" +
    "\uffdc\033\uffdc\040\uffdc\041\uffdc\042\uffdc\001\002\000\036" +
    "\017\uffdf\020\uffdf\021\044\022\045\023\uffdf\024\uffdf\025" +
    "\uffdf\026\uffdf\027\uffdf\031\uffdf\033\uffdf\040\uffdf\041\uffdf" +
    "\042\uffdf\001\002\000\010\017\042\020\041\033\052\001" +
    "\002\000\036\017\uffc4\020\uffc4\021\uffc4\022\uffc4\023\uffc4" +
    "\024\uffc4\025\uffc4\026\uffc4\027\uffc4\031\uffc4\033\uffc4\040" +
    "\uffc4\041\uffc4\042\uffc4\001\002\000\022\032\031\044\026" +
    "\045\034\046\035\047\032\050\040\051\027\052\037\001" +
    "\002\000\010\017\042\020\041\031\055\001\002\000\004" +
    "\036\uffc3\001\002\000\004\036\057\001\002\000\012\046" +
    "\065\047\062\051\061\052\064\001\002\000\006\030\066" +
    "\037\067\001\002\000\006\030\uffbc\037\uffbc\001\002\000" +
    "\006\030\uffbe\037\uffbe\001\002\000\006\030\uffc0\037\uffc0" +
    "\001\002\000\006\030\uffbd\037\uffbd\001\002\000\006\030" +
    "\uffbf\037\uffbf\001\002\000\012\046\065\047\062\051\061" +
    "\052\064\001\002\000\004\033\070\001\002\000\036\017" +
    "\uffc2\020\uffc2\021\uffc2\022\uffc2\023\uffc2\024\uffc2\025\uffc2" +
    "\026\uffc2\027\uffc2\031\uffc2\033\uffc2\040\uffc2\041\uffc2\042" +
    "\uffc2\001\002\000\006\030\uffc1\037\uffc1\001\002\000\022" +
    "\002\ufffa\004\ufffa\005\ufffa\006\ufffa\013\ufffa\014\ufffa\035" +
    "\ufffa\045\ufffa\001\002\000\024\032\031\043\074\044\026" +
    "\045\034\046\035\047\032\050\040\051\027\052\037\001" +
    "\002\000\022\032\031\044\026\045\034\046\035\047\032" +
    "\050\040\051\027\052\037\001\002\000\010\033\uffec\040" +
    "\125\041\126\001\002\000\022\017\042\020\041\023\123" +
    "\024\115\025\122\026\120\027\121\042\116\001\002\000" +
    "\004\033\100\001\002\000\004\034\101\001\002\000\016" +
    "\004\ufff2\005\ufff2\006\ufff2\013\ufff2\014\ufff2\045\ufff2\001" +
    "\002\000\016\004\006\005\022\006\004\013\005\014\014" +
    "\045\020\001\002\000\020\004\006\005\022\006\004\013" +
    "\005\014\014\035\105\045\020\001\002\000\022\002\ufffe" +
    "\004\ufffe\005\ufffe\006\ufffe\013\ufffe\014\ufffe\035\ufffe\045" +
    "\ufffe\001\002\000\024\002\uffed\004\uffed\005\uffed\006\uffed" +
    "\013\uffed\014\uffed\015\106\035\uffed\045\uffed\001\002\000" +
    "\004\034\ufff0\001\002\000\022\002\ufff1\004\ufff1\005\ufff1" +
    "\006\ufff1\013\ufff1\014\ufff1\035\ufff1\045\ufff1\001\002\000" +
    "\022\002\uffee\004\uffee\005\uffee\006\uffee\013\uffee\014\uffee" +
    "\035\uffee\045\uffee\001\002\000\004\034\112\001\002\000" +
    "\016\004\006\005\022\006\004\013\005\014\014\045\020" +
    "\001\002\000\020\004\006\005\022\006\004\013\005\014" +
    "\014\035\114\045\020\001\002\000\022\002\uffef\004\uffef" +
    "\005\uffef\006\uffef\013\uffef\014\uffef\035\uffef\045\uffef\001" +
    "\002\000\022\032\uffe5\044\uffe5\045\uffe5\046\uffe5\047\uffe5" +
    "\050\uffe5\051\uffe5\052\uffe5\001\002\000\022\032\uffe2\044" +
    "\uffe2\045\uffe2\046\uffe2\047\uffe2\050\uffe2\051\uffe2\052\uffe2" +
    "\001\002\000\022\032\031\044\026\045\034\046\035\047" +
    "\032\050\040\051\027\052\037\001\002\000\022\032\uffe6" +
    "\044\uffe6\045\uffe6\046\uffe6\047\uffe6\050\uffe6\051\uffe6\052" +
    "\uffe6\001\002\000\022\032\uffe1\044\uffe1\045\uffe1\046\uffe1" +
    "\047\uffe1\050\uffe1\051\uffe1\052\uffe1\001\002\000\022\032" +
    "\uffe4\044\uffe4\045\uffe4\046\uffe4\047\uffe4\050\uffe4\051\uffe4" +
    "\052\uffe4\001\002\000\022\032\uffe3\044\uffe3\045\uffe3\046" +
    "\uffe3\047\uffe3\050\uffe3\051\uffe3\052\uffe3\001\002\000\014" +
    "\017\042\020\041\033\uffe7\040\uffe7\041\uffe7\001\002\000" +
    "\022\032\031\044\026\045\034\046\035\047\032\050\040" +
    "\051\027\052\037\001\002\000\022\032\uffea\044\uffea\045" +
    "\uffea\046\uffea\047\uffea\050\uffea\051\uffea\052\uffea\001\002" +
    "\000\022\032\031\044\026\045\034\046\035\047\032\050" +
    "\040\051\027\052\037\001\002\000\004\033\uffe9\001\002" +
    "\000\004\033\uffeb\001\002\000\004\033\uffe8\001\002\000" +
    "\004\002\001\001\002\000\022\002\ufff9\004\ufff9\005\ufff9" +
    "\006\ufff9\013\ufff9\014\ufff9\035\ufff9\045\ufff9\001\002\000" +
    "\004\031\uffd9\001\002\000\004\031\uffd5\001\002\000\004" +
    "\031\uffda\001\002\000\004\031\uffd4\001\002\000\004\031" +
    "\uffd7\001\002\000\004\031\uffd6\001\002\000\004\031\uffd8" +
    "\001\002\000\004\032\145\001\002\000\024\032\031\043" +
    "\074\044\026\045\034\046\035\047\032\050\040\051\027" +
    "\052\037\001\002\000\004\033\ufff5\001\002\000\004\033" +
    "\150\001\002\000\004\034\151\001\002\000\016\004\006" +
    "\005\022\006\004\013\005\014\014\045\020\001\002\000" +
    "\020\004\006\005\022\006\004\013\005\014\014\035\ufff4" +
    "\045\020\001\002\000\004\035\154\001\002\000\022\002" +
    "\ufff3\004\ufff3\005\ufff3\006\ufff3\013\ufff3\014\ufff3\035\ufff3" +
    "\045\ufff3\001\002\000\004\045\156\001\002\000\006\025" +
    "\uffd0\030\uffd0\001\002\000\006\025\161\030\160\001\002" +
    "\000\004\045\174\001\002\000\004\007\162\001\002\000" +
    "\004\023\163\001\002\000\010\010\164\011\165\012\167" +
    "\001\002\000\006\025\uffcd\030\uffcd\001\002\000\006\025" +
    "\uffcb\030\uffcb\001\002\000\006\025\uffce\030\uffce\001\002" +
    "\000\006\025\uffcc\030\uffcc\001\002\000\006\025\172\030" +
    "\171\001\002\000\010\010\164\011\165\012\167\001\002" +
    "\000\022\002\uffd2\004\uffd2\005\uffd2\006\uffd2\013\uffd2\014" +
    "\uffd2\035\uffd2\045\uffd2\001\002\000\006\025\uffcf\030\uffcf" +
    "\001\002\000\006\025\uffd1\030\uffd1\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\172\000\024\002\011\003\012\004\020\005\015\012" +
    "\007\013\016\020\010\021\014\022\006\001\001\000\002" +
    "\001\001\000\004\031\143\001\001\000\004\026\137\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\020\004\020\005\103\012\007\013" +
    "\016\020\010\021\014\022\006\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\007\032\010\027\011" +
    "\035\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\007\050\010\027\011\035\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\010\047\011\035\001\001\000\006\010\042" +
    "\011\035\001\001\000\002\001\001\000\004\011\046\001" +
    "\001\000\004\011\045\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\007\053\010\027\011\035\001\001\000\002" +
    "\001\001\000\004\037\055\001\001\000\002\001\001\000" +
    "\006\027\057\030\062\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\030\070\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\007\075\010\027\011\035\014\076\015\074" +
    "\001\001\000\012\007\075\010\027\011\035\015\131\001" +
    "\001\000\002\001\001\000\004\016\116\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\034\101\001\001\000" +
    "\022\003\102\004\020\005\015\012\007\013\016\020\010" +
    "\021\014\022\006\001\001\000\020\004\020\005\103\012" +
    "\007\013\016\020\010\021\014\022\006\001\001\000\002" +
    "\001\001\000\006\006\107\017\106\001\001\000\004\035" +
    "\110\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\003\112\004\020\005\015\012\007\013" +
    "\016\020\010\021\014\022\006\001\001\000\020\004\020" +
    "\005\103\012\007\013\016\020\010\021\014\022\006\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\007\123\010\027\011\035\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\007\075\010\027\011\035\015" +
    "\130\001\001\000\004\036\126\001\001\000\012\007\075" +
    "\010\027\011\035\015\127\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\007\075\010" +
    "\027\011\035\014\145\015\074\001\001\000\004\032\146" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\003" +
    "\151\004\020\005\015\012\007\013\016\020\010\021\014" +
    "\022\006\001\001\000\022\004\020\005\103\012\007\013" +
    "\016\020\010\021\014\022\006\033\152\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\023\156\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\024\167\025\165\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\025\172\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol cur_token) {
        String errMsg = "Syntax error " + cur_token.value.toString() + " " + cur_token.right + ":" + cur_token.left + "\n";
        report_error(errMsg, null);
    }

    public void unrecovered_syntax_error(Symbol cur_token) throws Exception {
        String errMsg = "Couldn't repair and continue parse " + cur_token.value.toString() + " " + cur_token.right + ":" + cur_token.left + "\n";
        report_fatal_error(errMsg, null);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$AnalizadorSintactico$actions {


     public TablaDeSimbolos tablaDeSimbolos = new TablaDeSimbolos();
     public Queue<String> colaNombres = new LinkedList();
     public Queue<String> colaTipoDato = new LinkedList(); 
     public Stack<Integer> pila = new Stack<Integer>();
     public ArrayList<String> polaca = new ArrayList<String>();
     public String comparadorString = "";
     public int hayDobleComparacion= 0;
     public int isOr = 0;
     public Stack<Integer> posicionesBloqueVerdaderoOr = new Stack<Integer>();
     public int contador = 0;
     public int constanteAContar = 0;  
     public Polaca polacaManager = new Polaca();
     public void insertarEnPolaca(String contenido){
          polaca.add(contenido);
     }

     public String obtenerContrario(int posi){
          String original = polaca.get(posi);
          String contrario = ""; 
          switch(original){
               case "BLT": 
                    contrario= "BGE";
               break;
               case "BGE":
                    contrario= "BLT";
               break;
               case "BLE":
                    contrario= "BGT";
               break;
               case "BGT":
                    contrario= "BLE";
               break;
               case "BEQ":
                    contrario= "BNE";
               break;
               case "BNE":
                    contrario= "BEQ";
               break;
               default:
                    contrario= " ERROR ";
               break;

          }
          return contrario; 
     }

     public void insertarEnPolaca(String contenido, Integer lugar){
          polaca.set(lugar , contenido);
     }

     public void avanzar() {
          polaca.add(" ");
     }


  private final AnalizadorSintactico parser;

  /** Constructor */
  CUP$AnalizadorSintactico$actions(AnalizadorSintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintactico$do_action_part00000000(
    int                        CUP$AnalizadorSintactico$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintactico$parser,
    java.util.Stack            CUP$AnalizadorSintactico$stack,
    int                        CUP$AnalizadorSintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintactico$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Symbol start_val = (Symbol)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintactico$parser.done_parsing();
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= prog 
            {
              Symbol RESULT =null;
		  tablaDeSimbolos.guardarTabla();
                         System.out.println("R1: inicio -> prog");
                         System.out.println("COMPILACION EXITOSA!");
                         polacaManager.guardarPolaca(polaca); 
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // prog ::= sent 
            {
              Symbol RESULT =null;
		 
                         System.out.println("R2: prog -> sent");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("prog",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // prog ::= prog sent 
            {
              Symbol RESULT =null;
		
                         System.out.println("R3: prog -> prog sent");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("prog",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sent ::= asig PYC 
            {
              Symbol RESULT =null;
		 
                         System.out.println("R4: sent -> asig");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("sent",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sent ::= iteracion 
            {
              Symbol RESULT =null;
		
                         System.out.println("R5: sent -> iteracion");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("sent",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sent ::= dec 
            {
              Symbol RESULT =null;
		 
                         System.out.println("R6: sent -> dec");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("sent",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sent ::= sent_put PYC 
            {
              Symbol RESULT =null;
		 
                         System.out.println("R7: sent -> sent_put PYC");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("sent",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sent ::= sent_get PYC 
            {
              Symbol RESULT =null;
		 
                         System.out.println("R8: sent -> sent_get PYC");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("sent",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sent ::= seleccion 
            {
              Symbol RESULT =null;
		 
                      System.out.println("R9: sent -> seleccion");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("sent",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // asig ::= ID OP_AS expresion 
            {
              Symbol RESULT =null;
		int IDleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int IDright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		String ID = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int OP_ASleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int OP_ASright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		String OP_AS = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		 
                         insertarEnPolaca(ID);
                         insertarEnPolaca(OP_AS);
                         System.out.println("R10: asig -> ID OP_ASig expresion");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("asig",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$0 ::= 
            {
              Symbol RESULT =null;

                         pila.push(polaca.size());
                         insertarEnPolaca("ET");
                         RESULT = new Symbol(-1); 
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("NT$0",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // NT$1 ::= 
            {
              Symbol RESULT =(Symbol) ((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;

                         if(isOr != 0){
                           posicionesBloqueVerdaderoOr.push(polaca.size());
                         }
                         RESULT = new Symbol(-1); 
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("NT$1",24, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NT$2 ::= 
            {
              Symbol RESULT =(Symbol) ((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;

                         insertarEnPolaca("BI");
                         if(hayDobleComparacion != 0){
                             insertarEnPolaca(String.valueOf(polaca.size() + 1), pila.pop() );
                              if(isOr != 0){
                                   insertarEnPolaca(String.valueOf(posicionesBloqueVerdaderoOr.pop()), pila.pop());
                                   isOr--; 
                              } else {
                                   insertarEnPolaca(String.valueOf(polaca.size() + 1), pila.pop() );
                              }
                              hayDobleComparacion--; 
                         } else {
                         insertarEnPolaca(String.valueOf(polaca.size() + 1), pila.pop() );
                         }

                        insertarEnPolaca(String.valueOf(pila.pop()));

                         RESULT = new Symbol(-1); 
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("NT$2",25, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // iteracion ::= WHILE NT$0 PA condicion NT$1 PC LA prog NT$2 LC 
            {
              Symbol RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Symbol) ((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		 
                         System.out.println("R11: iteracion -> WHILE condicion  LA prog  lc");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("iteracion",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-9)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$3 ::= 
            {
              Symbol RESULT =null;

                    if(isOr!=0){
                         posicionesBloqueVerdaderoOr.push(polaca.size());
                    }
                    RESULT = new Symbol(-1); 
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("NT$3",26, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // seleccion ::= IF PA condicion PC LA NT$3 prog LC seleccion_else 
            {
              Symbol RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Symbol) ((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("seleccion",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NT$4 ::= 
            {
              Symbol RESULT =null;

                         insertarEnPolaca("BI");
                          insertarEnPolaca(String.valueOf(polaca.size()+1), pila.pop() );
                          if(hayDobleComparacion != 0){
                               if(isOr!=0){
                                    insertarEnPolaca(String.valueOf(posicionesBloqueVerdaderoOr.pop()), pila.pop() );
                                   isOr--;
                               }else {
                                    insertarEnPolaca(String.valueOf(polaca.size()+1), pila.pop() );
                               }
                               hayDobleComparacion--; 
                          }
                         pila.push(polaca.size() );
                         avanzar();
                         RESULT = new Symbol(-1); 
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("NT$4",27, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // seleccion_else ::= ELSE NT$4 LA prog LC 
            {
              Symbol RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Symbol) ((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		
                         insertarEnPolaca(String.valueOf(polaca.size()), pila.pop() );
                         System.out.println("R14: seleccion_else -> IF condicion LA prog LC ELSE prog");

                
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("seleccion_else",13, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // seleccion_else ::= vacio 
            {
              Symbol RESULT =null;
		 
                     if(hayDobleComparacion != 0){
                          insertarEnPolaca(String.valueOf(polaca.size()), pila.pop() );
                          if(isOr != 0){
                              insertarEnPolaca(String.valueOf(posicionesBloqueVerdaderoOr.pop()), pila.pop() );
                               isOr--;
                          } else {
                              insertarEnPolaca(String.valueOf(polaca.size()), pila.pop() );
                          }
                    
                         hayDobleComparacion--; 
                     } else {
                          insertarEnPolaca(String.valueOf(polaca.size()), pila.pop() );
                     }
                     System.out.println("If sin else"); 
                     RESULT = new Symbol(-1); 
                
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("seleccion_else",13, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // vacio ::= 
            {
              Symbol RESULT =null;
		
                    RESULT = new Symbol(-1);
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("vacio",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // condicion ::= comparacion 
            {
              Symbol RESULT =null;
		 
                         System.out.println("R15: condicion -> comparacion");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // condicion ::= comparacion OP_AND comparacion 
            {
              Symbol RESULT =null;
		 
                         hayDobleComparacion++; 
                         System.out.println("R16: condicion -> comparacion OP_AND  comparacion");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NT$5 ::= 
            {
              Symbol RESULT =null;
 
                         String contrario = obtenerContrario(polaca.size()-2);
                         isOr++;   
                         insertarEnPolaca(contrario, polaca.size() - 2);
                         RESULT = new Symbol(-1); 

                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("NT$5",28, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // condicion ::= comparacion OP_OR NT$5 comparacion 
            {
              Symbol RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Symbol) ((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		 
                         hayDobleComparacion++; 
                         System.out.println("R17: condicion -> comparacion OP_OR comparacion");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // condicion ::= OP_NOT comparacion 
            {
              Symbol RESULT =null;
		 
                         String contrario = obtenerContrario(polaca.size()-2);
                         insertarEnPolaca(contrario, polaca.size() - 2);
                          System.out.println("R18: condicion -> OP_NOT comparacion");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // comparacion ::= expresion comparador expresion 
            {
              Symbol RESULT =null;
		 
                        insertarEnPolaca("CMP");
                         insertarEnPolaca(comparadorString);
                         pila.push(polaca.size());
                         avanzar();
                          System.out.println("R19: comparacion -> expresion comparador expresion");
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comparacion",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // comparador ::= OP_MAYIG 
            {
              Symbol RESULT =null;
		  
                         comparadorString = "BLT"; 
                         System.out.println("comparador -> OP_MAYIG " );

		          
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // comparador ::= OP_MENIG 
            {
              Symbol RESULT =null;
		 
                         comparadorString = "BGT"; 
                         System.out.println("comparador -> OP_MENIG" );
		          
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // comparador ::= OP_MAY 
            {
              Symbol RESULT =null;
		 
                         comparadorString = "BLE"; 
                         System.out.println("comparador -> OP_MAY" );
		          
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // comparador ::= OP_MEN 
            {
              Symbol RESULT =null;
		 
                         comparadorString = "BGE"; 
                         System.out.println("comparador -> OP_MEN");
		          
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // comparador ::= OP_COMP 
            {
              Symbol RESULT =null;
		 
                         comparadorString = "BNE"; 
                         System.out.println("comparador -> OP_COMP" );
                      
		          
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // comparador ::= OP_DIST 
            {
              Symbol RESULT =null;
		 
                         comparadorString = "BEQ"; 
                         System.out.println("comparador -> OP_DIST" );
		          
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expresion ::= expresion OP_SUM termino 
            {
              Symbol RESULT =null;
		int OP_SUMleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int OP_SUMright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		String OP_SUM = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		
                    System.out.println("expresion -> expresion OP_SUM termino");
                    insertarEnPolaca(OP_SUM);    
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expresion ::= expresion OP_RES termino 
            {
              Symbol RESULT =null;
		int OP_RESleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int OP_RESright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		String OP_RES = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		
                    System.out.println("expresion -> expresion OP_RES termino");  
                    insertarEnPolaca(OP_RES);   
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion ::= termino 
            {
              Symbol RESULT =null;
		
                    System.out.println("expresion -> termino");

               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // termino ::= termino OP_DIV factor 
            {
              Symbol RESULT =null;
		int OP_DIVleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int OP_DIVright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		String OP_DIV = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		 
                    System.out.println("termino -> termino OP_DIV factor");
                    insertarEnPolaca(OP_DIV);
		     
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("termino",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // termino ::= termino OP_MUL factor 
            {
              Symbol RESULT =null;
		int OP_MULleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int OP_MULright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		String OP_MUL = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		 
                    System.out.println("termino -> termino OP_MUL factor");
                    insertarEnPolaca(OP_MUL);
		     
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("termino",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // termino ::= factor 
            {
              Symbol RESULT =null;
		 
                    System.out.println("termino -> factor");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("termino",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // variable ::= CONST_STR 
            {
              Symbol RESULT =null;
		int CONST_STRleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CONST_STRright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CONST_STR = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                    String stringSinComillas = CONST_STR.substring(1, CONST_STR.length() - 1);
                    tablaDeSimbolos.agregarEnTabla("_"+stringSinComillas, null, stringSinComillas, stringSinComillas.length());
                    System.out.println("variable -> CONST_STRING");
                    insertarEnPolaca(CONST_STR);
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("variable",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // variable ::= ID 
            {
              Symbol RESULT =null;
		int IDleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int IDright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String ID = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                         System.out.println("variable -> ID");
                         insertarEnPolaca(ID);
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("variable",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // variable ::= CONST_INT 
            {
              Symbol RESULT =null;
		int CONST_INTleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CONST_INTright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CONST_INT = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
                         tablaDeSimbolos.agregarEnTabla("_"+CONST_INT, null, CONST_INT, null);
                         System.out.println("variable -> CONST_INT");
                         insertarEnPolaca(CONST_INT);
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("variable",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // variable ::= CONST_FLOAT 
            {
              Symbol RESULT =null;
		int CONST_FLOATleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CONST_FLOATright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CONST_FLOAT = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
                         tablaDeSimbolos.agregarEnTabla("_"+CONST_FLOAT, null, CONST_FLOAT, null);
                         System.out.println("variable -> CONST_FLOAT");
                        insertarEnPolaca(CONST_FLOAT);
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("variable",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // variable ::= CTE_BIN 
            {
              Symbol RESULT =null;
		int CTE_BINleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CTE_BINright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CTE_BIN = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
                         String valorBin = CTE_BIN.substring(2);
                         String valorDecimal = String.valueOf(Integer.parseInt(valorBin,2));
                        insertarEnPolaca(valorDecimal);
                         tablaDeSimbolos.agregarEnTabla("_"+CTE_BIN, null, valorBin, null);
                         System.out.println("variable -> CTE_BIN");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("variable",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // variable ::= CTE_HEXA 
            {
              Symbol RESULT =null;
		int CTE_HEXAleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CTE_HEXAright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CTE_HEXA = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                         String valorHexa = CTE_HEXA.substring(2);
                         String valorDecimal = String.valueOf(Integer.parseInt(valorHexa,16));
                         insertarEnPolaca(valorDecimal);
                         tablaDeSimbolos.agregarEnTabla("_"+CTE_HEXA, null, valorDecimal, null);
                         System.out.println("variable -> CTE_HEXA");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("variable",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sent_put ::= PUT variable 
            {
              Symbol RESULT =null;
		int PUTleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int PUTright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		String PUT = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		
                    insertarEnPolaca(PUT);
                    System.out.println("sent_put -> PUT variable");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("sent_put",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sent_get ::= GET ID 
            {
              Symbol RESULT =null;
		int GETleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int GETright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		String GET = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int IDleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int IDright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String ID = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                    insertarEnPolaca(ID);
                    insertarEnPolaca(GET);
                    System.out.println("sent_get -> GET ID");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("sent_get",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // dec ::= DIM OP_MEN list_var OP_MAY AS OP_MEN list_td OP_MAY 
            {
              Symbol RESULT =null;
		
                    tablaDeSimbolos.agregarVariables(colaNombres, colaTipoDato);
                    System.out.println("dec -> DIM OP_MEN list_var OP_MAY AS OP_MEN list_td OP_MAY");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("dec",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-7)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // list_var ::= list_var COMA ID 
            {
              Symbol RESULT =null;
		int IDleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int IDright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String ID = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                         colaNombres.add(ID);
                         System.out.println("list_var -> list_var COMA ID: ");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("list_var",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // list_var ::= ID 
            {
              Symbol RESULT =null;
		int IDleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int IDright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String ID = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                    colaNombres.add(ID);
                     System.out.println("list_var -> ID ");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("list_var",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // list_td ::= list_td COMA tipo_dato 
            {
              Symbol RESULT =null;
		
                         System.out.println("list_td -> list_td COMA tipo_dato");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("list_td",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // list_td ::= tipo_dato 
            {
              Symbol RESULT =null;
		
                         System.out.println("list_td -> TIPO DE DATO ");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("list_td",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // tipo_dato ::= INTEGER 
            {
              Symbol RESULT =null;
		int INTEGERleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int INTEGERright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String INTEGER = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		   
                         colaTipoDato.add(INTEGER);
                         System.out.println("tipo_dato -> INTEGER");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // tipo_dato ::= FLOAT 
            {
              Symbol RESULT =null;
		int FLOATleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int FLOATright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String FLOAT = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                         colaTipoDato.add(FLOAT);
                         System.out.println("tipo_dato -> FLOAT");
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // tipo_dato ::= STRING 
            {
              Symbol RESULT =null;
		int STRINGleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int STRINGright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String STRING = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                         colaTipoDato.add(STRING);
                         System.out.println("tipo_dato -> STRING");
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // factor ::= ID 
            {
              Symbol RESULT =null;
		int IDleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int IDright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String ID = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
                    insertarEnPolaca(ID);
                    System.out.println("factor -> ID: " + ID);
                    System.out.println("ID: " + ID);
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // factor ::= CONST_INT 
            {
              Symbol RESULT =null;
		int CONST_INTleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CONST_INTright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CONST_INT = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                    insertarEnPolaca(CONST_INT);
                    tablaDeSimbolos.agregarEnTabla("_"+CONST_INT, null, CONST_INT, null);
                    System.out.println("factor -> CONST_INT: " + CONST_INT);
		          System.out.println("constante entera: " + CONST_INT);
		     
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= CONST_FLOAT 
            {
              Symbol RESULT =null;
		int CONST_FLOATleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CONST_FLOATright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CONST_FLOAT = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		   
                    insertarEnPolaca(CONST_FLOAT);
                    tablaDeSimbolos.agregarEnTabla("_"+CONST_FLOAT, null, CONST_FLOAT, null);
                    System.out.println("factor -> CONST_FLOAT: " + CONST_FLOAT);
		          System.out.println("constante flotante: " + CONST_FLOAT);
		     
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // factor ::= CONST_STR 
            {
              Symbol RESULT =null;
		int CONST_STRleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CONST_STRright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CONST_STR = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		  
                    insertarEnPolaca(CONST_STR);
                    String stringSinComillas = CONST_STR.substring(1, CONST_STR.length() - 1);
                    tablaDeSimbolos.agregarEnTabla("_"+stringSinComillas, null, stringSinComillas, stringSinComillas.length());
                    System.out.println("factor -> CONST_STR: " + CONST_STR);
		          System.out.println("constante CONST_STR: " + CONST_STR);
		     
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // factor ::= CTE_BIN 
            {
              Symbol RESULT =null;
		int CTE_BINleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CTE_BINright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CTE_BIN = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                    String valorBin = CTE_BIN.substring(2);
                    String valorDecimal = String.valueOf(Integer.parseInt(valorBin,2));
                    insertarEnPolaca(valorDecimal);
                    tablaDeSimbolos.agregarEnTabla("_"+CTE_BIN, null, valorBin, null);
                    System.out.println("factor -> cte_bin: " + CTE_BIN);
		          System.out.println("constante CTE_BIN: " + CTE_BIN);
		     
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // factor ::= CTE_HEXA 
            {
              Symbol RESULT =null;
		int CTE_HEXAleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CTE_HEXAright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CTE_HEXA = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
                    String valorHexa = CTE_HEXA.substring(2);
                    String valorDecimal = String.valueOf(Integer.parseInt(valorHexa,16));
                    insertarEnPolaca(valorDecimal);
                    tablaDeSimbolos.agregarEnTabla("_"+CTE_HEXA, null, valorDecimal, null);
                    System.out.println("factor -> CTE_HEXA: " + CTE_HEXA);
		          System.out.println("constante CTE_HEXA: " + CTE_HEXA);
		     
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // factor ::= PA expresion PC 
            {
              Symbol RESULT =null;
		
                    System.out.println("factor -> PA expresion PC");
		     
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // NT$6 ::= 
            {
              Symbol RESULT =null;

                    tablaDeSimbolos.agregarEnTabla("@constanteAContar", null, null, null);
                    tablaDeSimbolos.agregarEnTabla("@contador", "Integer", null, null);
                   insertarEnPolaca("@constanteAContar");
                   insertarEnPolaca(":");
                   insertarEnPolaca("0");
                   insertarEnPolaca("@contador");
                   insertarEnPolaca(":");
                   RESULT = new Symbol(-1); 

               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("NT$6",29, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // factor ::= CONTAR PA expresion PYC NT$6 CA list_constantes CC PC 
            {
              Symbol RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Symbol) ((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).value;
		
                 System.out.println("factor -> CONTAR PA expresion PYC CA list_exp CC PC");
                     insertarEnPolaca("@contador");
                    RESULT = new Symbol(-1); 
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // list_constantes ::= list_constantes COMA constantes 
            {
              Symbol RESULT =null;
		  
                 insertarEnPolaca("@constanteAContar");
                   insertarEnPolaca("CMP");
                    insertarEnPolaca("BNE");
                    pila.push(polaca.size());
                    avanzar();
                    insertarEnPolaca("1");
                    insertarEnPolaca("@contador");
                    insertarEnPolaca("+");
                    insertarEnPolaca("@contador");
                    insertarEnPolaca(":");
                    insertarEnPolaca(String.valueOf(polaca.size()), pila.pop());
                    System.out.println("list_constantes -> list_constantes COMA constantes");
                    RESULT = new Symbol(-1); 
   
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("list_constantes",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // list_constantes ::= constantes 
            {
              Symbol RESULT =null;
		 
                   insertarEnPolaca("@constanteAContar");
                   insertarEnPolaca("CMP");
                    insertarEnPolaca("BNE");
                    pila.push(polaca.size());
                    avanzar();
                    insertarEnPolaca("1");
                    insertarEnPolaca("@contador");
                    insertarEnPolaca("+");
                    insertarEnPolaca("@contador");
                    insertarEnPolaca(":");
                    insertarEnPolaca(String.valueOf(polaca.size()), pila.pop());
                    System.out.println("list_constantes -> constantes");
                     RESULT = new Symbol(-1); 
               
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("list_constantes",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // constantes ::= CONST_INT 
            {
              Symbol RESULT =null;
		int CONST_INTleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CONST_INTright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CONST_INT = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                          insertarEnPolaca(CONST_INT);
                          System.out.println("Constante: "+ CONST_INT);
                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("constantes",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // constantes ::= CONST_FLOAT 
            {
              Symbol RESULT =null;
		int CONST_FLOATleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CONST_FLOATright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CONST_FLOAT = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                          insertarEnPolaca(CONST_FLOAT);
                            System.out.println("Constante: "+ CONST_FLOAT);

                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("constantes",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // constantes ::= CTE_BIN 
            {
              Symbol RESULT =null;
		int CTE_BINleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CTE_BINright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CTE_BIN = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                          insertarEnPolaca(CTE_BIN);
                          System.out.println("Constante: "+ CTE_BIN);

                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("constantes",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // constantes ::= CTE_HEXA 
            {
              Symbol RESULT =null;
		int CTE_HEXAleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int CTE_HEXAright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String CTE_HEXA = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
                          insertarEnPolaca(CTE_HEXA);
                         System.out.println("Constante: "+ CTE_HEXA);

                    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("constantes",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnalizadorSintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintactico$do_action(
    int                        CUP$AnalizadorSintactico$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintactico$parser,
    java.util.Stack            CUP$AnalizadorSintactico$stack,
    int                        CUP$AnalizadorSintactico$top)
    throws java.lang.Exception
    {
              return CUP$AnalizadorSintactico$do_action_part00000000(
                               CUP$AnalizadorSintactico$act_num,
                               CUP$AnalizadorSintactico$parser,
                               CUP$AnalizadorSintactico$stack,
                               CUP$AnalizadorSintactico$top);
    }
}

}
