
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int OP_MENIG = 18;
  public static final int PUT = 2;
  public static final int OP_AS = 12;
  public static final int OP_MAYIG = 20;
  public static final int CONTAR = 34;
  public static final int INTEGER = 6;
  public static final int PC = 25;
  public static final int OP_NOT = 33;
  public static final int OP_AND = 30;
  public static final int PA = 24;
  public static final int CTE_HEXA = 39;
  public static final int OP_DIV = 16;
  public static final int CTE_BIN = 40;
  public static final int GET = 3;
  public static final int CONST_FLOAT = 37;
  public static final int OP_MUL = 15;
  public static final int CC = 29;
  public static final int IF = 10;
  public static final int CA = 28;
  public static final int ID = 35;
  public static final int DIM = 4;
  public static final int EOF = 0;
  public static final int LC = 27;
  public static final int LA = 26;
  public static final int error = 1;
  public static final int COMA = 22;
  public static final int OP_OR = 31;
  public static final int OP_MEN = 17;
  public static final int ELSE = 11;
  public static final int OP_SUM = 13;
  public static final int WHILE = 9;
  public static final int FLOAT = 8;
  public static final int OP_MAY = 19;
  public static final int STRING = 7;
  public static final int OP_COMP = 32;
  public static final int CONST_STR = 38;
  public static final int AS = 5;
  public static final int OP_DIST = 21;
  public static final int CONST_INT = 36;
  public static final int PYC = 23;
  public static final int OP_RES = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUT",
  "GET",
  "DIM",
  "AS",
  "INTEGER",
  "STRING",
  "FLOAT",
  "WHILE",
  "IF",
  "ELSE",
  "OP_AS",
  "OP_SUM",
  "OP_RES",
  "OP_MUL",
  "OP_DIV",
  "OP_MEN",
  "OP_MENIG",
  "OP_MAY",
  "OP_MAYIG",
  "OP_DIST",
  "COMA",
  "PYC",
  "PA",
  "PC",
  "LA",
  "LC",
  "CA",
  "CC",
  "OP_AND",
  "OP_OR",
  "OP_COMP",
  "OP_NOT",
  "CONTAR",
  "ID",
  "CONST_INT",
  "CONST_FLOAT",
  "CONST_STR",
  "CTE_HEXA",
  "CTE_BIN"
  };
}

